Repository boostcampwm-2024/iOS09-BeStory, pull requests merged in 2024-11, with the labels that each got.

#8 [FEAT]: P2P Socket을 통해 유저 연결 혹은 끊김 정보를 제공하는 로직 구현
  App/App.xcodeproj/project.pbxproj
  App/App/Info.plist
  Data/Data.xcodeproj/project.pbxproj
  Data/Data/BrowsingUserRepository.swift
  Data/Data/Dummy.swift
  Data/DataInterface/Dummy.swift
  Data/P2PSocket/MCPeerIDStorage.swift
  Data/P2PSocket/SocketPeer.swift
  Data/P2PSocket/SocketProvider.swift
  Data/SocketProvider/Dummy.swift
  Domain/Domain.xcodeproj/project.pbxproj
  Domain/Domain/Dummy.swift
  Domain/DomainInterface/Dummy.swift
  Domain/Entity/BrowsedUser.swift
  Domain/Interfaces/BrowsingUserUseCaseInterface.swift
  Domain/Interfaces/RepositoryInterface/BrowsingUserRepositoryInterface.swift
  Domain/UseCase/BrowsingUserUseCase.swift
  Domain/UseCase/Info.plist
  Domain/UseCaseTest/BrowsingUserUseCaseTest.swift
  Domain/UseCaseTest/MockBrowinsgUseCase.swift
  Domain/UseCaseTest/MockBrowsingUserRepository.swift
  Domain/UseCaseTest/MockSocketProvider.swift
  Feature/Feature.xcodeproj/project.pbxproj
Labels: docs, test, feature

#10 [Feature/#7] 사용자가 불러온 비디오를 확인할 수 있는 리스트 UI 설계
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/Helper/EventPublisher.swift
  Feature/Feature/Helper/ReadOnlyPublisher.swift
  Feature/Feature/Helper/UIColor+HexInitialization.swift
  Feature/Feature/VideoDetailView/VideoDetailViewController.swift
  Feature/Feature/VideoListView/Components/CollectionView/VideoListCollectionViewCell.swift
  Feature/Feature/VideoListView/Components/CollectionView/VideoListDataSource.swift
  Feature/Feature/VideoListView/Components/CollectionView/VideoListItem.swift
  Feature/Feature/VideoListView/Components/CollectionView/VideoListSection.swift
  Feature/Feature/VideoListView/Components/IconButton.swift
  Feature/Feature/VideoListView/Components/VideoListHeaderView.swift
  Feature/Feature/VideoListView/VideoListViewController.swift
  Feature/Feature/VideoListView/ViewModel/MockVideoListViewModel.swift
  Feature/Feature/VideoListView/ViewModel/MultipeerVideoListViewModel.swift
  Feature/Feature/VideoListView/ViewModel/VideoListViewModel.swift
Labels: feature

#12 [Feature/#11] 참여자의 상태 및 참가자수를 리턴하는 기능 추가
  Data/Data/ConnectedUserRepository.swift
  Domain/Entity/ConnectedUser.swift
  Domain/Interfaces/ConnectedUserUseCaseInterface.swift
  Domain/Interfaces/RepositoryInterface/ConnectedUserRepositoryInterface.swift
  Domain/UseCase/ConnectedUserUseCase.swift
Labels: feature

#15 [Feature/#4] 레이더 형태로 주변 유저 목록을 표시하는 UI 설계
  Data/Data.xcodeproj/project.pbxproj
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/ConnectionView/CGPoint+Extension.swift
  Feature/Feature/ConnectionView/ConnectionViewController.swift
  Feature/Feature/ConnectionView/View/CustomCircleView.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewInputOutput.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewModel.swift
Labels: feature

#32 [CHORE]: PR 관련 이벤트에 슬랙 알림을 보내주는 action 추가
  .github/workflows/slackPing.yml
Labels: chore

#30 [Feature/#17] 초대 로직 구현
  App/App/Info.plist
  Data/Data.xcodeproj/project.pbxproj
  Data/Data/BrowsingUserRepository.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/Domain.xcodeproj/project.pbxproj
  Domain/Entity/ConnectedUser.swift
  Domain/Entity/InvitedUser.swift
  Domain/Interfaces/BrowsingUserUseCaseInterface.swift
  Domain/Interfaces/RepositoryInterface/BrowsingUserRepositoryInterface.swift
  Domain/Interfaces/RepositoryInterface/ConnectedUserRepositoryInterface.swift
  Domain/Interfaces/UseCaseInterface/BrowsingUserUseCaseInterface.swift
  Domain/Interfaces/UseCaseInterface/ConnectedUserUseCaseInterface.swift
  Domain/UseCase/BrowsingUserUseCase.swift
  Domain/UseCaseTest/BrowsingUserUseCaseTest.swift
  Domain/UseCaseTest/MockBrowinsgUseCase.swift
  Domain/UseCaseTest/MockBrowsingUserRepository.swift
  Domain/UseCaseTest/MockSocketProvider.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature.xcodeproj/xcshareddata/xcschemes/GroupInfoTest.xcscheme
  Feature/FeatureInterface/Dummy.swift
Labels: feature

#33 [Feature/#14] 비디오 선택 및 업로드, 상세보기 화면 구현
  App/App.xcodeproj/project.pbxproj
  App/App/SceneDelegate.swift
  Data/Data.xcodeproj/project.pbxproj
  Data/Data/ConnectedUserRepository.swift
  Domain/Interfaces/UseCaseInterface/ConnectedUserUseCaseInterface.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/Helper/AVAsset+Metadata.swift
  Feature/Feature/Helper/AVAsset+Thumbnail.swift
  Feature/Feature/Helper/EventPublisher.swift
  Feature/Feature/Helper/VideoManager.swift
  Feature/Feature/VideoDetailView/VideoDetailViewController.swift
  Feature/Feature/VideoListView/VideoListViewController.swift
  Feature/Feature/VideoListView/View/CollectionView/VideoListCollectionViewCell.swift
  Feature/Feature/VideoListView/View/CollectionView/VideoListDataSource.swift
  Feature/Feature/VideoListView/View/CollectionView/VideoListItem.swift
  Feature/Feature/VideoListView/View/CollectionView/VideoListSection.swift
  Feature/Feature/VideoListView/View/IconButton.swift
  Feature/Feature/VideoListView/View/VideoListHeaderView.swift
  Feature/Feature/VideoListView/ViewModel/MockVideoListViewModel.swift
  Feature/Feature/VideoListView/ViewModel/MultipeerVideoListViewModel.swift
  Feature/Feature/VideoListView/ViewModel/VideoListViewInput.swift
  Feature/Feature/VideoListView/ViewModel/VideoListViewModel.swift
  Feature/Feature/VideoListView/ViewModel/VideoListViewOutput.swift
Labels: feature

#38 [Feature/#13] 비디오 업/다운로드 로직 구현
  Data/Data.xcodeproj/project.pbxproj
  Data/Data/SharingVideoRepository.swift
  Data/P2PSocket/Counter.swift
  Data/P2PSocket/ResourceValidator.swift
  Data/P2PSocket/SharedResource.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/Domain.xcodeproj/project.pbxproj
  Domain/Entity/SharedVideo.swift
  Domain/Interfaces/RepositoryInterface/SharingVideoRepositoryInterface.swift
Labels: refactor, feature

#40 [Fix/#39] 깃헙핑 - 리뷰어에게 여러 번 알림이 오는 버그 수정
  .github/workflows/slackPing.yml
Labels: fix

#41 [REFACTORING/#36] Socket에서 유저 상태 수정
  App/App/SceneDelegate.swift
  Data/Data.xcodeproj/project.pbxproj
  Data/Data/BrowsingUserRepository.swift
  Data/Data/ConnectedUserRepository.swift
  Data/P2PSocket/SocketPeer.swift
  Data/P2PSocket/SocketProvidable.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/Domain.xcodeproj/project.pbxproj
  Domain/Entity/ConnectedUser.swift
  Domain/Interfaces/RepositoryInterface/BrowsingUserRepositoryInterface.swift
  Domain/Interfaces/RepositoryInterface/SharingVideoRepositoryInterface.swift
  Domain/Interfaces/UseCaseInterface/BrowsingUserUseCaseInterface.swift
  Domain/Interfaces/UseCaseInterface/ConnectedUserUseCaseInterface.swift
  Domain/UseCase/BrowsingUserUseCase.swift
  Domain/UseCase/ConnectedUserUseCase.swift
  Feature/Feature.xcodeproj/project.pbxproj
Labels: refactor

#46 [Fix/#45] 다이나믹 로딩 안되는 문제 해결
  App/App.xcodeproj/project.pbxproj
  App/App/Info.plist
  Data/Data.xcodeproj/project.pbxproj
  Domain/Domain.xcodeproj/project.pbxproj
  Feature/Feature.xcodeproj/project.pbxproj
Labels: fix

#43 [Feature/#35] invite 관련 세부 UI 연결
  App/App.xcodeproj/project.pbxproj
  App/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme
  Core/Core.xcodeproj/project.pbxproj
  Data/Data.xcodeproj/project.pbxproj
  Data/Data.xcodeproj/xcshareddata/xcschemes/Data.xcscheme
  Data/P2PSocket/SocketProvider.swift
  Domain/Entity/BrowsedUser.swift
  Domain/Entity/ConnectedUser.swift
  Domain/Entity/InvitedUser.swift
  Domain/UseCase/BrowsingUserUseCase.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/ConnectionView/ConnectionViewController.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewInputOutput.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewModel.swift
  Feature/Feature/Helper/AVAsset+Thumbnail.swift
  Feature/Feature/Helper/EventPublisher.swift
  Feature/Feature/Helper/UIColor+HexInitialization.swift
Labels: feature

#49 [Feature/#47] 그룹 참여자들의 상태를 보여주는 뷰와 UseCase 연결
  App/App/Info.plist
  App/App/SceneDelegate.swift
  Core/Core.xcodeproj/project.pbxproj
  Data/P2PSocket/SocketProvider.swift
  Domain/UseCase/ConnectedUserUseCase.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/GroupInfoView/GroupInfoViewController.swift
  Feature/Feature/GroupInfoView/View/ParticipantCountView.swift
  Feature/Feature/GroupInfoView/View/ParticipantInfoView.swift
  Feature/Feature/GroupInfoView/ViewModel/GroupInfoViewInput.swift
  Feature/Feature/GroupInfoView/ViewModel/GroupInfoViewModel.swift
  Feature/Feature/GroupInfoView/ViewModel/GroupInfoViewOutput.swift
Labels: refactor, feature

#50 [Feature/#48] MainViewController를 구현하여 UI의 흐름을 연결한다
  App/App/SceneDelegate.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/UseCase/BrowsingUserUseCase.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/ConnectionView/ConnectionViewController.swift
  Feature/Feature/ConnectionView/View/CustomCircleView.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewInputOutput.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewModel.swift
  Feature/Feature/GroupInfoView/GroupInfoViewController.swift
  Feature/Feature/GroupInfoView/InvitedUser.swift
  Feature/Feature/GroupInfoView/View/ParticipantInfoView.swift
  Feature/Feature/Helper/EmojiManager.swift
  Feature/Feature/Helper/UIAlertController+Types.swift
  Feature/Feature/MainViewController.swift
Labels: feature

#52 [Chore/#51] Dynamic Framework Embeded 옵션 수정 및 의존성 수정
  App/App.xcodeproj/project.pbxproj
  Data/Data.xcodeproj/project.pbxproj
  Domain/Domain.xcodeproj/project.pbxproj
  Feature/Feature.xcodeproj/project.pbxproj
Labels: refactor, chore

#57 [Feature/#44] 동영상 리스트 UseCase 작성 + 동기화 로직
  App/App/AppDelegate.swift
  App/App/SceneDelegate.swift
  Core/Utilities/FileSystemManager.swift
  Core/Utilities/VideoManager.swift
  Data/Data.xcodeproj/project.pbxproj
  Data/Data/SharingVideoRepository.swift
  Data/P2PSocket/SocketProvidable.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/Domain.xcodeproj/project.pbxproj
  Domain/Interfaces/RepositoryInterface/SharingVideoRepositoryInterface.swift
  Domain/Interfaces/UseCaseInterface/VideoUseCaseInterface.swift
  Domain/UseCase/ConnectedUserUseCase.swift
  Domain/UseCase/VideoUseCase.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/VideoListView/TempViewController.swift
  Feature/Feature/VideoListView/VideoListViewController.swift
  Feature/Feature/VideoListView/ViewModel/MockVideoListViewModel.swift
  Feature/Feature/VideoListView/ViewModel/MultipeerVideoListViewModel.swift
  Feature/Feature/VideoListView/ViewModel/VideoListViewInput.swift
  Feature/Feature/VideoListView/ViewModel/VideoListViewOutput.swift
Labels: feature

#59 [Feature/#58] 그룹 퇴장 기능 로직 구현 및 UI 연결
  Data/Data/ConnectedUserRepository.swift
  Data/P2PSocket/SocketProvidable.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/Interfaces/RepositoryInterface/ConnectedUserRepositoryInterface.swift
  Domain/Interfaces/UseCaseInterface/ConnectedUserUseCaseInterface.swift
  Domain/UseCase/ConnectedUserUseCase.swift
  Feature/Feature/GroupInfoView/GroupInfoViewController.swift
  Feature/Feature/GroupInfoView/ViewModel/GroupInfoViewModel.swift
  Feature/Feature/MovieEditView/MovieEditViewController.swift
  Feature/Feature/MovieEditView/ViewModel/MovieEditViewMInput.swift
  Feature/Feature/MovieEditView/ViewModel/MovieEditViewMOutput.swift
  Feature/Feature/MovieEditView/ViewModel/MovieEditViewModel.swift
Labels: feature

#63 [Feature/#62] CRDT 구현
  Data/CRDT/LWWElementSet.swift
  Data/CRDT/Timestamp.swift
  Data/Data.xcodeproj/project.pbxproj
Labels: feature

#61 [Feature/#60] 공유 편집화면을 위한 뷰컨트롤러 및 동영상 재생 뷰 구현
  Core/Core.xcodeproj/project.pbxproj
  Core/Extentions/UIView+Image.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/VideoEditView/VideoEditViewController.swift
  Feature/Feature/VideoEditView/View/HeightResizableSlider.swift
  Feature/Feature/VideoEditView/View/VideoPlayerView.swift
  Feature/Feature/VideoEditView/ViewModel/SharedVideoEditViewInput.swift
  Feature/Feature/VideoEditView/ViewModel/SharedVideoEditViewModel.swift
  Feature/Feature/VideoEditView/ViewModel/SharedVideoEditViewOutput.swift
Labels: feature

#65 [Feature/#56] 동영상 동기화 로직 구현
  App/App/AppDelegate.swift
  Core/Utilities/FileSystemManager.swift
  Core/Utilities/Synchronizer.swift
  Data/Data.xcodeproj/project.pbxproj
  Data/Data/SharingVideoRepository.swift
  Data/P2PSocket/SocketProvidable.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/Interfaces/RepositoryInterface/SharingVideoRepositoryInterface.swift
  Domain/UseCase/VideoUseCase.swift
Labels: feature

#67 [Feature/#66] 영상 타임라인을 나타낼 수 있는 UI
  App/App/SceneDelegate.swift
  Data/CRDT/LWWElementSet.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/ConnectionView/ConnectionViewController.swift
  Feature/Feature/MovieEditView/MovieEditViewController.swift
  Feature/Feature/MovieEditView/ViewModel/MovieEditViewMInput.swift
  Feature/Feature/MovieEditView/ViewModel/MovieEditViewMOutput.swift
  Feature/Feature/MovieEditView/ViewModel/MovieEditViewModel.swift
  Feature/Feature/SharedVideoEditView/SharedVideoEditViewController.swift
  Feature/Feature/SharedVideoEditView/View/CollectionView/VideoTimelineCollectionViewCell.swift
  Feature/Feature/SharedVideoEditView/View/CollectionView/VideoTimelineDataSource.swift
  Feature/Feature/SharedVideoEditView/View/CollectionView/VideoTimelineItem.swift
  Feature/Feature/SharedVideoEditView/View/CollectionView/VideoTimelineSection.swift
  Feature/Feature/SharedVideoEditView/View/HeightResizableSlider.swift
  Feature/Feature/SharedVideoEditView/View/VideoPlayerView.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewInput.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewModel.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewOutput.swift
  Feature/Feature/VideoEditView/VideoEditViewController.swift
  Feature/Feature/VideoListView/VideoListViewController.swift
Labels: feature
