Repository boostcampwm-2024/iOS09-BeStory, pull requests merged in 2024-12, with the labels that each got.

#73 [Feature/#64] 편집화면 SliderBar 구현
  App/App.xcodeproj/project.pbxproj
  App/App/Info.plist
  Core/Core.xcodeproj/project.pbxproj
  Core/Extentions/Double+bound.swift
  Core/Utilities/Combine+withUnretainedSink.swift
  Core/Utilities/UIImageWrapper.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/Helper/AVAssetImageGenerator+generateImage.swift
  Feature/Feature/Helper/BeStoryReactive/BeStoryReactive.swift
  Feature/Feature/Helper/BeStoryReactive/UIButton+BSReactive.swift
  Feature/Feature/Helper/BeStoryReactive/UIStackView+AddArangeSubViews.swift
  Feature/Feature/Helper/RoundButton.swift
  Feature/Feature/Helper/UIImage+Concat.swift
  Feature/Feature/Helper/UIImage+convertColor.swift
  Feature/Feature/Helper/UIImage+resize.swift
  Feature/Feature/Helper/UIView+Extension.swift
  Feature/Feature/PresentationModel/VideoPresentationModel.swift
  Feature/Feature/SharedVideoEditView/SharedVideoEditViewController.swift
  Feature/Feature/SharedVideoEditView/View/EditOptionButton.swift
  Feature/Feature/SharedVideoEditView/View/OptionButtonStackView.swift
  Feature/Feature/SharedVideoEditView/View/VideoPlayer/HeightResizableSlider.swift
  Feature/Feature/SharedVideoEditView/View/VideoPlayer/VideoPlayerView.swift
  Feature/Feature/SharedVideoEditView/View/VideoTrimmingSliderBar/ImageFrameBlurView.swift
  Feature/Feature/SharedVideoEditView/View/VideoTrimmingSliderBar/ImageFrameView.swift
  Feature/Feature/SharedVideoEditView/View/VideoTrimmingSliderBar/SliderThumb.swift
  Feature/Feature/SharedVideoEditView/View/VideoTrimmingSliderBar/VideoTrimmingSliderBar.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewModel.swift
  Feature/Feature/VideoListView/View/CollectionView/VideoListCollectionViewCell.swift
Labels: feature

#72 [Feature/#68] VectorClock 구현 및 LWWElementSet에 적용
  Data/CRDT/LWWElementSet.swift
  Data/CRDT/Timestamp.swift
  Data/CRDT/VectorClock.swift
  Data/CRDTTest/CRDTTest.swift
  Data/Data.xcodeproj/project.pbxproj
  Domain/Domain.xcodeproj/project.pbxproj
Labels: refactor, feature

#81 [Refactoring/#75] P2PSocket 리팩토링
  App/App/Info.plist
  Core/Extentions/Info.plist
  Data/Data.xcodeproj/project.pbxproj
  Data/Data/BrowsingUserRepository.swift
  Data/Data/ConnectedUserRepository.swift
  Data/Data/DataMapper.swift
  Data/Data/Info.plist
  Data/Data/SharingVideoRepository.swift
  Data/P2PSocket/Counter.swift
  Data/P2PSocket/ResourceValidator.swift
  Data/P2PSocket/SharedResource.swift
  Data/P2PSocket/SocketProvidable.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/Domain.xcodeproj/project.pbxproj
  Domain/Entity/SharedVideo.swift
  Domain/Interfaces/RepositoryInterface/SharingVideoRepositoryInterface.swift
  Domain/UseCase/Info.plist
  Domain/UseCase/VideoUseCase.swift
  Feature/Feature/GroupInfoView/GroupInfoViewController.swift
  Feature/Feature/SharedVideoEditView/SharedVideoEditViewController.swift
  Feature/Feature/SharedVideoEditView/View/VideoTrimmingSliderBar/VideoTrimmingSliderBar.swift
Labels: refactor, feature

#80 [Feature/#77] 동영상 타임라인 드래그 앤 드롭 구현
  Feature/Feature/SharedVideoEditView/SharedVideoEditViewController.swift
  Feature/Feature/SharedVideoEditView/View/CollectionView/VideoTimelineItem.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewInput.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewModel.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewOutput.swift
Labels: feature

#84 [Feature/#74] CRDT Socket에 연결 및 UseCase
  App/App/SceneDelegate.swift
  Core/Utilities/FileSystemManager.swift
  Data/CRDT/LWWElementSet.swift
  Data/CRDT/VectorClock.swift
  Data/CRDTTest/CRDTTest.swift
  Data/Data.xcodeproj/project.pbxproj
  Data/Data/BrowsingUserRepository.swift
  Data/Data/DataMapper.swift
  Data/Data/DataMapper/DataMapper.swift
  Data/Data/EditVideoRepository.swift
  Data/Data/Element/EditVideoElement.swift
  Data/Data/SharingVideoRepository.swift
  Data/P2PSocket/MCPeerIDStorage.swift
  Data/P2PSocket/SharedResource.swift
  Data/P2PSocket/SocketProvidable.swift
  Data/P2PSocket/SocketProvider.swift
  Data/P2PSocket/URL+Extension/URL+Extension.swift
  Domain/Entity/SharedVideo.swift
  Domain/Entity/Video.swift
  Domain/Interfaces/RepositoryInterface/EditVideoRepositoryInterface.swift
  Domain/Interfaces/UseCaseInterface/BrowsingUserUseCaseInterface.swift
  Domain/Interfaces/UseCaseInterface/ConnectedUserUseCaseInterface.swift
  Domain/Interfaces/UseCaseInterface/EditVideoUseCaseInterface.swift
  Domain/Interfaces/UseCaseInterface/SharingVideoUseCaseInterface.swift
  Domain/UseCase/ConnectedUserUseCase.swift
  Domain/UseCase/VideoUseCase.swift
  Feature/Feature/ConnectionView/ConnectionViewController.swift
  Feature/Feature/VideoListView/ViewModel/MockVideoListViewModel.swift
  Feature/Feature/VideoListView/ViewModel/MultipeerVideoListViewModel.swift
Labels: feature

#85 [Feature/#76] 공유 편집화면에서 실시간 변경사항을 UI에 반영한다.
  App/App/SceneDelegate.swift
  Core/Utilities/FileSystemManager.swift
  Data/CRDT/LWWElementSet.swift
  Data/CRDT/VectorClock.swift
  Data/Data/DataMapper/DataMapper.swift
  Data/Data/EditVideoRepository.swift
  Data/Data/Element/EditVideoElement.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/Interfaces/RepositoryInterface/EditVideoRepositoryInterface.swift
  Domain/Interfaces/UseCaseInterface/EditVideoUseCaseInterface.swift
  Domain/UseCase/VideoUseCase.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewInput.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewOutput.swift
  Feature/Feature/Helper/Sequence+AsyncCompactMap.swift
  Feature/Feature/PresentationModel/VideoPresentationModel.swift
  Feature/Feature/SharedVideoEditView/SharedVideoEditViewController.swift
  Feature/Feature/SharedVideoEditView/View/CollectionView/VideoTimelineItem.swift
  Feature/Feature/SharedVideoEditView/View/VideoPlayer/VideoPlayerView.swift
  Feature/Feature/SharedVideoEditView/View/VideoTrimmingSliderBar/VideoTrimmingSliderBar.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewInput.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewModel.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewOutput.swift
Labels: feature

#89 [Feature/#88] 타임라인 프리뷰 및 파일 저장 기능 구현
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/SharedVideoEditView/VideoMerger/VideoMerger.swift
Labels: feature

#90 [Feature/#83] 동영상 리스트 정보가 정상적으로 뜨게 변경 및 타임라인 뷰와 연결
  App/App/SceneDelegate.swift
  Data/Data/SharingVideoRepository.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/Interfaces/RepositoryInterface/SharingVideoRepositoryInterface.swift
  Domain/UseCase/VideoUseCase.swift
  Feature/Feature/SharedVideoEditView/SharedVideoEditViewController.swift
  Feature/Feature/SharedVideoEditView/View/CollectionView/VideoTimelineCollectionViewCell.swift
  Feature/Feature/SharedVideoEditView/View/VideoPlayer/VideoPlayerView.swift
  Feature/Feature/VideoListView/VideoListViewController.swift
  Feature/Feature/VideoListView/ViewModel/MultipeerVideoListViewModel.swift
Labels: refactor

#94 [Fix/#86] Socket에서 발생했었던 버그 해결
  Data/Data/BrowsingUserRepository.swift
  Data/Data/ConnectedUserRepository.swift
  Data/Data/DataMapper/DataMapper.swift
  Data/Data/Element/EditVideoElement.swift
  Data/P2PSocket/SocketPeer.swift
  Data/P2PSocket/SocketProvidable.swift
  Data/P2PSocket/SocketProvider.swift
  Domain/Entity/ConnectedUser.swift
  Domain/Interfaces/RepositoryInterface/BrowsingUserRepositoryInterface.swift
  Domain/Interfaces/UseCaseInterface/BrowsingUserUseCaseInterface.swift
  Domain/UseCase/BrowsingUserUseCase.swift
  Domain/UseCase/ConnectedUserUseCase.swift
  Feature/Feature/ConnectionView/ConnectionViewController.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewModel.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewOutput.swift
  Feature/Feature/GroupInfoView/View/ParticipantInfoView.swift
  Feature/Feature/GroupInfoView/ViewModel/GroupInfoViewModel.swift
Labels: fix

#95 [Feature/#82] 순서 변경 및 길이 편집 로직 보완 및 UI연결
  Data/Data/Element/EditVideoElement.swift
  Domain/UseCase/VideoUseCase.swift
  Feature/Feature/PresentationModel/VideoPresentationModel.swift
  Feature/Feature/SharedVideoEditView/SharedVideoEditViewController.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewInput.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewModel.swift
Labels: feature

#97 [Feature/#87] Coordinator 적용 및 나가기 버튼 구현
  App/App/AppLifeCycles/AppDelegate.swift
  App/App/AppLifeCycles/SceneDelegate.swift
  App/App/MainContainer.swift
  App/App/MainCoordinator.swift
  App/App/MainViewController.swift
  App/App/RootViewController.swift
  App/App/SceneDelegate.swift
  Core/Utilities/BaseCoordinator/Container.swift
  Core/Utilities/BaseCoordinator/Coordinator.swift
  Core/Utilities/DIContainer.swift
  Data/CRDTTest/CRDTTest.swift
  Data/Data/DataMapper/DataMapper.swift
  Data/Data/EditVideoRepository.swift
  Data/Data/SharingVideoRepository.swift
  Domain/UseCase/VideoUseCase.swift
  Feature/Feature.xcodeproj/project.pbxproj
  Feature/Feature/ConnectionView/ConnectionCoordinator.swift
  Feature/Feature/ConnectionView/ConnectionViewContainer.swift
  Feature/Feature/ConnectionView/ConnectionViewController.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewModel.swift
  Feature/Feature/ConnectionView/ViewModel/ConnectionViewOutput.swift
  Feature/Feature/GroupInfoView/GroupInfoContainer.swift
  Feature/Feature/GroupInfoView/GroupInfoCoordinator.swift
  Feature/Feature/GroupInfoView/GroupInfoViewController.swift
  Feature/Feature/GroupInfoView/ViewModel/GroupInfoViewModel.swift
  Feature/Feature/MainViewController.swift
  Feature/Feature/PreviewView/PreviewContainer.swift
  Feature/Feature/PreviewView/PreviewCoordinator.swift
  Feature/Feature/PreviewView/PreviewViewController.swift
  Feature/Feature/PreviewView/ViewModel/PreviewViewModel.swift
  Feature/Feature/SharedVideoEditView/SharedVideoEditContainer.swift
  Feature/Feature/SharedVideoEditView/SharedVideoEditCoordinator.swift
  Feature/Feature/SharedVideoEditView/SharedVideoEditViewController.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewInput.swift
  Feature/Feature/SharedVideoEditView/ViewModel/SharedVideoEditViewModel.swift
  Feature/Feature/VideoListView/TempViewController.swift
  Feature/Feature/VideoListView/VideoListContainer.swift
  Feature/Feature/VideoListView/VideoListCoordinator.swift
  Feature/Feature/VideoListView/VideoListViewController.swift
  Feature/Feature/VideoListView/ViewModel/MockVideoListViewModel.swift
  Feature/Feature/VideoListView/ViewModel/MultipeerVideoListViewModel.swift
Labels: refactor, feature
